---
version: '2'
services:
  vault:
    image: vault
    privileged: true
    volumes:
      - ./misc:/misc
    ports:
      - "8200:8200"
      - "8201:8201"
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_LOCAL_CONFIG: '{"listener" : { "tcp" : {"address" : "0.0.0.0:8201", "tls_cert_file" : "/misc/devserver.crt", "tls_key_file" : "/misc/devserver.key" } } }'

  vault-ui:
    build: .
    ports:
      - "8000:8000"
    links:
      - vault
    volumes:
      - .:/app
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      VAULT_URL_DEFAULT: http://vault:8200
      VAULT_AUTH_DEFAULT: USERNAMEPASSWORD
#      VAULT_SUPPLIED_TOKEN_HEADER: 'X-Remote-User'

  webpack:
    build: .
    volumes:
      - .:/app
    command: yarn run dev-pack
